[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sep_cnn_fer"
version = "0.1.0"

[tool.setuptools]
packages = ["Data", "ModelArchitectures", "Experiments", "ExplainableAI"]